### ISSUE TITLE
Player Listening

### ISSUE THREAD

**Issue by MeLike2D** [gregorious-j/SenkuBot#1]
https://github.com/gregorious-j/SenkuBot/blob/b4c1f7ee0613f7b6b1d41c941d1530dd421f44d6/src/music/queueInstance.js#L118-L130

Instead of calling playTrack *(on line 128)* use the Player#play method because whenever a song ends it adds the two listeners (end and error) which will cause a memory leak and possibly do other things..

**Comment by gregorious-j** [comment]
Ah, good catch. I'll also change back() and skip() to do this as well.
